import {
  mdiAccount,
  mdiAccountMinus,
  mdiAccountMultiple,
  mdiAlert,
  mdiApps,
  mdiArchive,
  mdiArrowDown,
  mdiArrowExpandVertical,
  mdiArrowLeft,
  mdiArrowRight,
  mdiBook,
  mdiBookmark,
  mdiBookmarkCheck,
  mdiBookmarkMultiple,
  mdiBrightness6,
  mdiCancel,
  mdiCheck,
  mdiChevronDoubleDown,
  mdiChevronDoubleLeft,
  mdiChevronDoubleUp,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCloseCircle,
  mdiCodeBraces,
  mdiCodeGreaterThan,
  mdiCog,
  mdiCogs,
  mdiCommentMultipleOutline,
  mdiCommentOffOutline,
  mdiCommentQuote,
  mdiCommentTextMultipleOutline,
  mdiCrown,
  mdiDelete,
  mdiDotsHorizontal,
  mdiDownload,
  mdiEmail,
  mdiEmoticonOutline,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFile,
  mdiFileChart,
  mdiFileImage,
  mdiFileMusic,
  mdiFileUpload,
  mdiFileVideo,
  mdiFormatTitle,
  mdiGithub,
  mdiGoogle,
  mdiHistory,
  mdiHome,
  mdiImageMultiple,
  mdiInformation,
  mdiInformationOutline,
  mdiKeyChain,
  mdiLink,
  mdiLock,
  mdiLockOpenOutline,
  mdiMagnify,
  mdiMicrophone,
  mdiMicrophoneOff,
  mdiMusicNote,
  mdiNotebook,
  mdiOpenid,
  mdiPaletteOutline,
  mdiPause,
  mdiPencil,
  mdiPencilOutline,
  mdiPhone,
  mdiPhoneHangup,
  mdiPhoneOutline,
  mdiPictureInPictureBottomRight,
  mdiPin,
  mdiPlay,
  mdiPlus,
  mdiPlusCircle,
  mdiPlusCircleOutline,
  mdiQrcode,
  mdiSend,
  mdiSlack,
  mdiSnowflake,
  mdiStar,
  mdiStop,
  mdiTag,
  mdiTagMultiple,
  mdiToggleSwitch,
  mdiToggleSwitchOff,
  mdiTuneVertical,
  mdiVideo,
  mdiVideoOff,
  mdiVolumeHigh,
  mdiVolumeOff
} from '@mdi/js'

interface MdiIconsMapping {
  [name: string]: string
}

const mdi: MdiIconsMapping = {
  home: mdiHome,
  send: mdiSend,
  file: mdiFile,
  close: mdiClose,
  'close-circle': mdiCloseCircle,
  google: mdiGoogle,
  github: mdiGithub,
  openid: mdiOpenid,
  slack: mdiSlack,
  phone: mdiPhone,
  'phone-outline': mdiPhoneOutline,
  'phone-hangup': mdiPhoneHangup,
  microphone: mdiMicrophone,
  'microphone-off': mdiMicrophoneOff,
  pin: mdiPin,
  search: mdiMagnify,
  history: mdiHistory,
  'file-upload': mdiFileUpload,
  'file-music': mdiFileMusic,
  'file-video': mdiFileVideo,
  'file-image': mdiFileImage,
  'plus-circle-outline': mdiPlusCircleOutline,
  'dots-horizontal': mdiDotsHorizontal,
  book: mdiBook,
  notebook: mdiNotebook,
  tag: mdiTag,
  tags: mdiTagMultiple,
  email: mdiEmail,
  plus: mdiPlus,
  'plus-circle': mdiPlusCircle,
  download: mdiDownload,
  'emoticon-outline': mdiEmoticonOutline,
  cog: mdiCog,
  account: mdiAccount,
  'account-multiple': mdiAccountMultiple,
  'account-minus': mdiAccountMinus,
  cogs: mdiCogs,
  'brightness-6': mdiBrightness6,
  pencil: mdiPencil,
  'pencil-outline': mdiPencilOutline,
  'toggle-switch-off': mdiToggleSwitchOff,
  'toggle-switch-on': mdiToggleSwitch,
  'chevron-double': mdiChevronDoubleLeft,
  'chevron-double-up': mdiChevronDoubleUp,
  'chevron-double-down': mdiChevronDoubleDown,
  'chevron-down': mdiChevronDown,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  'chevron-up': mdiChevronUp,
  bookmark: mdiBookmark,
  'bookmark-multiple': mdiBookmarkMultiple,
  'bookmark-check': mdiBookmarkCheck,
  link: mdiLink,
  qrcode: mdiQrcode,
  apps: mdiApps,
  lock: mdiLock,
  'lock-open': mdiLockOpenOutline,
  check: mdiCheck,
  tune: mdiTuneVertical,
  'comment-multiple-outline': mdiCommentMultipleOutline,
  star: mdiStar,
  'info-outline': mdiInformationOutline,
  'comment-quote': mdiCommentQuote,
  info: mdiInformation,
  alert: mdiAlert,
  archive: mdiArchive,
  play: mdiPlay,
  pause: mdiPause,
  'volume-high': mdiVolumeHigh,
  'volume-off': mdiVolumeOff,
  'picture-in-picture-bottom-right': mdiPictureInPictureBottomRight,
  snowflake: mdiSnowflake,
  cancel: mdiCancel,
  'eye-outline': mdiEyeOutline,
  'eye-off-outline': mdiEyeOffOutline,
  'file-chart': mdiFileChart,
  'key-chain': mdiKeyChain,
  'code-grater-than': mdiCodeGreaterThan,
  'arrow-expand-vertical': mdiArrowExpandVertical,
  'image-multiple': mdiImageMultiple,
  'arrow-left': mdiArrowLeft,
  'arrow-right': mdiArrowRight,
  'arrow-down': mdiArrowDown,
  'music-note': mdiMusicNote,
  stop: mdiStop,
  crown: mdiCrown,
  'format-title': mdiFormatTitle,
  'code-braces': mdiCodeBraces,
  delete: mdiDelete,
  video: mdiVideo,
  'video-off': mdiVideoOff,
  'comment-outline': mdiCommentTextMultipleOutline,
  'comment-off-outline': mdiCommentOffOutline,
  'palette-outline': mdiPaletteOutline
}

export default mdi
