import {
  mdiHome,
  mdiSend,
  mdiFileUpload,
  mdiFile,
  mdiFileMusic,
  mdiFileVideo,
  mdiFileImage,
  mdiClose,
  mdiPlusCircleOutline,
  mdiGoogle,
  mdiGithub,
  mdiPhone,
  mdiPhoneHangup,
  mdiPhoneOutline,
  mdiMicrophone,
  mdiMicrophoneOff,
  mdiPin,
  mdiBellOutline,
  mdiDotsHorizontal,
  mdiBook,
  mdiTwitter,
  mdiTagMultiple,
  mdiEmail,
  mdiTag,
  mdiPlus,
  mdiMagnify,
  mdiHistory,
  mdiDownload,
  mdiEmoticonOutline,
  mdiCog,
  mdiAccount,
  mdiCogs,
  mdiBrightness6,
  mdiPencilOutline,
  mdiToggleSwitchOff,
  mdiToggleSwitch,
  mdiChevronDoubleLeft,
  mdiChevronLeft,
  mdiChevronRight,
  mdiBookmark,
  mdiBookmarkMultiple,
  mdiBookmarkCheck,
  mdiLink,
  mdiQrcode,
  mdiApps,
  mdiLock,
  mdiLockOpenOutline,
  mdiCheck,
  mdiTuneVertical,
  mdiCommentMultipleOutline,
  mdiStar,
  mdiInformationOutline,
  mdiCommentQuote
} from '@mdi/js'

interface MdiIconsMapping {
  [name: string]: string
}

const mdi: MdiIconsMapping = {
  home: mdiHome,
  send: mdiSend,
  file: mdiFile,
  close: mdiClose,
  google: mdiGoogle,
  github: mdiGithub,
  phone: mdiPhone,
  'phone-outline': mdiPhoneOutline,
  'phone-hangup': mdiPhoneHangup,
  microphone: mdiMicrophone,
  'microphone-off': mdiMicrophoneOff,
  pin: mdiPin,
  'bell-outline': mdiBellOutline,
  search: mdiMagnify,
  history: mdiHistory,
  'file-upload': mdiFileUpload,
  'file-music': mdiFileMusic,
  'file-video': mdiFileVideo,
  'file-image': mdiFileImage,
  'plus-circle-outline': mdiPlusCircleOutline,
  'dots-horizontal': mdiDotsHorizontal,
  book: mdiBook,
  twitter: mdiTwitter,
  tag: mdiTag,
  tags: mdiTagMultiple,
  email: mdiEmail,
  plus: mdiPlus,
  download: mdiDownload,
  'emoticon-outline': mdiEmoticonOutline,
  cog: mdiCog,
  account: mdiAccount,
  cogs: mdiCogs,
  'brightness-6': mdiBrightness6,
  pencil: mdiPencilOutline,
  'toggle-switch-off': mdiToggleSwitchOff,
  'toggle-switch-on': mdiToggleSwitch,
  'chevron-double': mdiChevronDoubleLeft,
  'chevron-left': mdiChevronLeft,
  'chevron-right': mdiChevronRight,
  bookmark: mdiBookmark,
  'bookmark-multiple': mdiBookmarkMultiple,
  'bookmark-check': mdiBookmarkCheck,
  link: mdiLink,
  qrcode: mdiQrcode,
  apps: mdiApps,
  lock: mdiLock,
  'lock-open': mdiLockOpenOutline,
  check: mdiCheck,
  tune: mdiTuneVertical,
  'comment-multiple-outline': mdiCommentMultipleOutline,
  star: mdiStar,
  info: mdiInformationOutline,
  'comment-quote': mdiCommentQuote
}

export default mdi
