name: Build preview image

on:
  pull_request:

jobs:
  build-preview-image:
    name: Build Preview Image
    runs-on: ubuntu-latest
    steps:
      - name: Set PR_NUMBER env
        run: echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          outputs: type=oci,dest=/tmp/image.tar

      - name: Save PR info
        run: |
          echo "${{ github.event.number }}" > /tmp/pr_number
          echo "${{ github.event.pull_request.head.sha }}" > /tmp/pr_sha

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.3.0
        with:
          name: preview-artifacts
          path: |
            /tmp/image.tar
            /tmp/pr_number
            /tmp/pr_sha
